DROP TABLE PAGING;
DROP SEQUENCE PAGINGSEQ;

CREATE SEQUENCE PAGINGSEQ;
CREATE TABLE PAGING(
SEQ NUMBER PRIMARY KEY,
WRITER VARCHAR2 NOT NULL,
TITLE VARCHAR2 NOT NULL,
CONTENT VARCHAR2 NOT NULL,
REGDATE DATE NOT NULL
);

INSERT INTO PAGING
VALUES(PAGINGSEQ.NEXTVAL,'admin','TEST 제목', 'TEST 내용',SYSDATE);

SELECT * FROM PAGING ORDER BY SEQ DESC;

SELECT B.*




