


DROP SEQUENCE MEMBERSEQ;
DROP TABLE MYMEMBER;

CREATE SEQUENCE MEMBERSEQ;

CREATE TABLE MYMEMBER(
MEMBERNO NUMBER PRIMARY KEY,
MEMBERID VARCHAR2(500) UNIQUE,
MEMBERPW VARCHAR2(1000) NOT NULL,
MEMBERNAME VARCHAR2(1000) NOT NULL,
MEMBERADDR VARCHAR2(4000) NOT NULL,
MEMBERPHONE VARCHAR2(20) NOT NULL,
MEMBEREMAIL VARCHAR2(100) NOT NULL,
MEMBERENABLED VARCHAR2(2) NOT NULL,
MEMBERROLE VARCHAR2(100) NOT NULL,
CONSTRAINT MENABLED_C CHECK(MEMBERENABLED IN('Y','N'))
);




INSERT INTO MYMEMBER VALUES(MEMBERSEQ.NEXTVAL,'admin','1234','관리자','한남동','010-1111-1111','YYY@NAVER.COM','Y','ADMIN');


SELECT * FROM MYMEMBER;