DROP SEQUENCE SEQSEQ;
DROP TABLE MYBOARD2;

CREATE SEQUENCE SEQSEQ;

CREATE TABLE MYBOARD2(
SEQ NUMBER PRIMARY KEY,
NAME VARCHAR2(1000) NOT NULL,
TITLE VARCHAR2(2000) NOT NULL,
CONTENT VARCHAR2(4000) NOT NULL,
MYDATE DATE NOT NULL
);

INSERT INTO MYBOARD2
VALUES(SEQSEQ.NEXTVAL,'관리자','스프링MVC TEST','SPRING MVC 참 쉽죠',SYSDATE);

SELECT * FROM MYBOARD2 ORDER BY SEQ DESC;