DROP SEQUENCE MYNOSEQ;

DROP TABLE MYBOARD1;

CREATE SEQUENCE MYNOSEQ;

CREATE TABLE MYBOARD1(
MYNO NUMBER PRIMARY KEY,
MYNAME VARCHAR2(1000) NOT NULL,
MYTITLE VARCHAR2(2000) NOT NULL,
MYCONTENT VARCHAR2(4000) NOT NULL,
MYDATE DATE NOT NULL

);

INSERT INTO MYBOARD1
VALUES(MYNOSEQ.NEXTVAL,'관리자','스프링MVC TEST','SPRING MVC 참 쉽죠',SYSDATE);

SELECT * FROM MYBOARD1 ORDER BY MYNO DESC;

