DROP SEQUENCE JDBCBOARDSEQ;

DROP TABLE JDBCBOARD;

CREATE SEQUENCE JDBCBOARDSEQ;

CREATE TABLE JDBCBOARD(
SEQ NUMBER PRIMARY KEY,
WRITER VARCHAR(500) NOT NULL,
TITLE VARCHAR(1000) NOT NULL,
CONTENT VARCHAR(2000) NOT NULL,
REGDATE DATE NOT NULL
);

INSERT INTO JDBCBOARD VALUES(JDBCBOARDSEQ.NEXTVAL,'관리자','TEST','TEST1234',SYSDATE);

SELECT * FROM JDBCBOARD
ORDER BY SEQ DESC;